# mysql
mysql:
    image: mysql:5.7
    volumes:
        - ./docker-assets/mysql/custom.cnf:/etc/mysql/conf.d/custom.cnf
        - ./mysql_data:/var/lib/mysql
    ports:
        - "3306:3306"
    environment:
        MYSQL_ROOT_PASSWORD: secret
        MYSQL_DATABASE: homestead
        MYSQL_USER: homestead
        MYSQL_PASSWORD: secret
